name:  Publish artifacts

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish artifact
        uses: ncipollo/release-action@v1
        with:
          artifacts: '*.AppImage*, *.exe'
          bodyFile: "body.md"