name: Build Windows Installer

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Install yq
      run: choco install yq

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version-file: pubspec.yaml
    - name: Install dependencies
      run: flutter pub get

    - name: Decode MSIX certificate
      run: echo $CERTIFICATE_BASE64 | base64 --decode > certificate.pfx
      env:
        CERTIFICATE_BASE64: ${{ secrets.MSIX_CERTIFICATE_BASE64 }}

    - name: Debug [TEMP !!!]
      run: echo $(( ${#PASS} * 6 ))
      env:
        PASS: ${{ secrets.MSIX_CERTIFICATE_PASSWORD }}

    - name: Use MSIX certificate
      env:
        APP_VERSION: 4.0.138.0
        MSIX_CERTIFICATE_PATH: certificate.pfx
        MSIX_CERTIFICATE_PASSWORD: ${{ secrets.MSIX_CERTIFICATE_PASSWORD }}
      run: flutter pub run msix:create --display-name Basic Chess Endgames --publisher-display-name Laurent Bernabe --identity-name com.loloof64.basicchessendgames --logo-path assets/images/logo.png --trim-logo false --languages en,fr,es --version $APP_VERSION --certificate-path $MSIX_CERTIFICATE_PATH --certificate-password $MSIX_CERTIFICATE_PASSWORD

    - name: Upload installer artifact
      uses: actions/upload-artifact@v4
      with:
        name: BasicChessEndgames-${{ github.ref_name }}-x86_64.msix
        path: build/msix/*.msix