name: Build Windows Installer

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Install yq
      run: choco install yq

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version-file: pubspec.yaml
    - name: Install dependencies
      run: flutter pub get

    - name: Decode MSIX certificate
      shell: pwsh
      run: |
        if ([string]::IsNullOrWhiteSpace($env:CERTIFICATE_SECRET)) {
          throw "Empty or invalid certificate."
        }
        try {
          $decodedBytes = [Convert]::FromBase64String($env:CERTIFICATE_SECRET)
        }
        catch {
          throw "Error while decoding certificate."
        }
        $outputFile = "msix_cert.pfx"
        [IO.File]::WriteAllBytes($outputFile, $decodedBytes)
      env:
        CERTIFICATE_SECRET: ${{ secrets.MSIX_CERTIFICATE_BASE64 }}

    - name: Use MSIX certificate
      env:
        MSIX_CERTIFICATE_PATH: msix_cert.pfx
        MSIX_CERTIFICATE_PASSWORD: ${{ secrets.MSIX_CERTIFICATE_PASSWORD }}
      run: flutter pub run msix:create

    - name: Upload installer artifact
      uses: actions/upload-artifact@v4
      with:
        name: BasicChessEndgames-${{ github.ref_name }}-x86_64.msix
        path: build/msix/*.msix