name: Build Windows Installer

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-2022
    
    steps:
    - uses: actions/checkout@v3

    - name: Install yq
      run: choco install yq

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version-file: pubspec.yaml
    - name: Install dependencies
      run: flutter pub get

    - name: Install WSL and base64
      run: |
        wsl --install -d Ubuntu-24.04
        wsl sudo apt-get update
        wsl sudo apt-get install coreutils

    - name: Decode MSIX certificate
      run: wsl echo "${{ secrets.MSIX_CERTIFICATE_BASE64 }}" | base64 -d > msix_cert.pfx

    - name: Get the certificate in the filesystem
      run: wsl cp msix_cert.pfx /mnt/c/
      

    - name: Use MSIX certificate
      env:
        MSIX_CERTIFICATE_PATH: /c/msix_cert.pfx
        MSIX_CERTIFICATE_PASSWORD: ${{ secrets.MSIX_CERTIFICATE_PASSWORD }}
      run: flutter pub run msix:create

    - name: Upload installer artifact
      uses: actions/upload-artifact@v4
      with:
        name: BasicChessEndgames-${{ github.ref_name }}-x86_64.msix
        path: build/msix/*.msix