name: Build Windows Installer

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Install yq
      run: choco install yq

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version-file: pubspec.yaml
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build Windows application
      run: flutter build windows --release
    
    - name: Create installer
      run: iscc "windows\inno_setup.iss"

    - name: Upload installer artifact
      uses: actions/upload-artifact@v4
      with:
        name: BasicChessEndgames-${{ github.ref_name }}-x86_64.exe
        path: build/windows/installer/BasicChessEndgames.exe